/*
 * Copyright 2018 Manjot Sidhu <manjot.techie@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.ibmhackchallenge.methodtraceanalyser;

import java.io.File;
import java.io.IOException;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;

/**
 * The heart of method trace analyser
 *
 * @author manjotsidhu
 */
public class Analyser {

    private final ArrayList analysedTime = new ArrayList();
    private final ArrayList analysedTimeMethods = new ArrayList();
    private final ArrayList analysedNMethods = new ArrayList();

    Analyser(ArrayList<String> files) throws IOException {
        analysedTime.add(analysedTimeMethods);
        boolean firstItr = true;

        for (String file : files) {
            ArrayList parsedLog = Parser.parse(new File(file));

            ArrayList<String> parsedTime = (ArrayList<String>) parsedLog.get(0);
            ArrayList parsedText = (ArrayList) parsedLog.get(1);
            ArrayList<Integer> parsedSequence = (ArrayList) parsedLog.get(2);
            Integer nMethods = parsedSequence.size() / 2;

            analyseTime(nMethods, parsedTime, parsedText, parsedSequence);
            analyseNMethods(parsedText, parsedSequence, analysedTimeMethods, firstItr);
            analyseCodeFlow(parsedText, parsedSequence);
            firstItr = false;
        }
    }

    /**
     * Analysis for time taken by every method of every log.
     *
     * @param nMethods number of methods exist in the log
     * @param parsedTime time of each methods at entry and exit parsed by the
     * parser
     * @param parsedText message of each event and methods in the log
     * @param parsedSequence sequence of methods donated by unique numbers
     * generated by parser
     * {@link com.github.ibmhackchallenge.methodtraceanalyser.parser}
     */
    private void analyseTime(Integer nMethods, ArrayList<String> parsedTime, ArrayList parsedText, ArrayList parsedSequence) {

        ArrayList results = new ArrayList();

        for (int iteration = 1; iteration <= nMethods; iteration++) {
            int firstIndex = Tools.find(parsedSequence, 0, iteration);
            int secondIndex = Tools.find(parsedSequence, firstIndex + 1, iteration);

            long timeTaken = ChronoUnit.MILLIS.between(LocalTime.parse(parsedTime.get(firstIndex)), LocalTime.parse(parsedTime.get(secondIndex)));
            Integer methodOccur = Tools.find(analysedTimeMethods, 0, (String) parsedText.get(firstIndex));

            if (methodOccur == 0 | (results.size() > methodOccur && results.get(methodOccur) != null)) {
                analysedTimeMethods.add(parsedText.get(firstIndex));
                results.add(timeTaken);
            } else {
                results.add(methodOccur, timeTaken);
            }
        }
        analysedTime.add(results);
    }

    /**
     * Returns the results of time taken by methods
     * {@link com.github.ibmhackchallenge.methodtraceanalyser.analyser#analyseTime(ArrayList parsedLog)}
     * which is stored in a private variable.
     *
     * @return ArrayList analysedTime
     */
    public ArrayList getAnalysedTime() {
        return analysedTime;
    }

    /**
     * Analysis number of times methods are executed.
     *
     * @param parsedText message of each event and methods in the log parsed by
     * parser
     * @param parsedSequence sequence of methods donated by unique numbers
     * generated by parser
     * {@link com.github.ibmhackchallenge.methodtraceanalyser.parser}
     */
    private void analyseNMethods(ArrayList parsedText, ArrayList parsedSequence, ArrayList analysedTimeMethods, boolean firstItr) {
        ArrayList results = new ArrayList();
        ArrayList<String> methods = (firstItr) ? Tools.removeDuplicates(analysedTimeMethods) : (ArrayList<String>) analysedNMethods.get(0);
        
        if(firstItr) {
            analysedNMethods.add(methods);
        }

        for (int iteration = 1; iteration <= methods.size(); iteration++) {
            int timeIndex = Tools.find(parsedSequence, 0, iteration);
            results.add(Tools.find(methods, 0, (String) parsedText.get(timeIndex)), Tools.count(parsedText, (String) parsedText.get(timeIndex)));
        }

        analysedNMethods.add(results);
    }

    /**
     * getanalysedNMethods returns the results of analyseNMethods
     * {@link com.github.ibmhackchallenge.methodtraceanalyser.analyser#analyseNMethods(ArrayList parsedText, ArrayList parsedSequence)}
     *
     * @return ArrayList analysedNMethods
     */
    public ArrayList getanalysedNMethods() {
        return analysedNMethods;
    }
    
    /**
     * Testing purpose only
     */
    private void analyseCodeFlow(ArrayList parsedText, ArrayList<Integer> parsedSequence) throws IOException {
        CodeFlow frame = new CodeFlow(parsedText, parsedSequence);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(900, 720);
        frame.setVisible(true);
        
    }

    /**
     * For testing purpose only.
     *
     * @param args null
     * @throws IOException
     */
    public static void main(String[] args) throws IOException {
        ArrayList<String> in = new ArrayList<>();
        in.add("sample_logs/log1");
        in.add("sample_logs/log2");

        Analyser an = new Analyser(in); 
        //System.out.println(Arrays.deepToString(an.getanalysedNMethods().toArray()));
    }
}
