/*
 * Copyright 2018 Sidhu.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.ibmhackchallenge.methodtraceanalyser;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sidhu
 */
public class Main extends javax.swing.JFrame {
    Analyser analyse;
    File[] logFiles;
    DefaultListModel<File> filesList = new DefaultListModel<>();
    File SampleLogFilesFolder = new File("./sample_logs");

    /**
     * Creates new form MainAlt
     */
    public Main() {
        initComponents();
        //resetInputForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GUI_main_panel = new javax.swing.JPanel();
        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanel_tab_home = new javax.swing.JPanel();
        jPanel5_main = new javax.swing.JPanel();
        jPanel_browse = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        browseBtn = new javax.swing.JButton();
        jPanel_listing_files = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2_text = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jList_listOfFiles = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel_InputForm_buttons = new javax.swing.JPanel();
        resetBtn = new javax.swing.JButton();
        analyseBtn = new javax.swing.JButton();
        jPanel_tab_1 = new javax.swing.JPanel();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_tab_2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        GUI_top_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        GUI_bottom_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Method Trace Analyser");
        setName("AppGUI"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        GUI_main_panel.setLayout(new java.awt.BorderLayout());

        jTabbedPaneMain.setMaximumSize(null);

        jPanel_tab_home.setName(""); // NOI18N
        jPanel_tab_home.setLayout(new java.awt.GridBagLayout());

        jPanel5_main.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5_main.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Please click on browse button to select log file(s) you want to analyse");
        jLabel1.setToolTipText("");
        jPanel_browse.add(jLabel1);

        browseBtn.setText("Browse...");
        browseBtn.setToolTipText("Click to browse and select log files");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });
        jPanel_browse.add(browseBtn);

        jPanel5_main.add(jPanel_browse, new java.awt.GridBagConstraints());

        jPanel_listing_files.setRequestFocusEnabled(false);
        jPanel_listing_files.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel_listing_files.add(jPanel6, gridBagConstraints);

        jLabel2_text.setText("List of selected files to analyse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel_listing_files.add(jLabel2_text, gridBagConstraints);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel_listing_files.add(jPanel7, gridBagConstraints);

        jList_listOfFiles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jList_listOfFiles.setMaximumSize(null);
        jList_listOfFiles.setMinimumSize(null);
        jList_listOfFiles.setName(""); // NOI18N
        jList_listOfFiles.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel_listing_files.add(jList_listOfFiles, gridBagConstraints);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel_listing_files.add(jPanel5, gridBagConstraints);

        jPanel8.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel_listing_files.add(jPanel8, gridBagConstraints);

        jPanel9.setMaximumSize(null);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel_listing_files.add(jPanel9, gridBagConstraints);

        jPanel10.setMaximumSize(null);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel_listing_files.add(jPanel10, gridBagConstraints);

        jPanel11.setMaximumSize(null);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel_listing_files.add(jPanel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel5_main.add(jPanel_listing_files, gridBagConstraints);

        resetBtn.setText("Clear");
        resetBtn.setToolTipText("To clear all files from selection");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel_InputForm_buttons.add(resetBtn);

        analyseBtn.setText("Analyse");
        analyseBtn.setName("analyseBtn"); // NOI18N
        analyseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyseBtnActionPerformed(evt);
            }
        });
        jPanel_InputForm_buttons.add(analyseBtn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel5_main.add(jPanel_InputForm_buttons, gridBagConstraints);

        jPanel_tab_home.add(jPanel5_main, new java.awt.GridBagConstraints());

        jTabbedPaneMain.addTab("Input trace logs", jPanel_tab_home);

        jPanel_tab_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setMaximumSize(null);
        jTable1.setMinimumSize(null);
        jTable1.setName(""); // NOI18N
        jTable1.setPreferredSize(null);
        jPanel_tab_1.add(jTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 40));

        jLabel2.setText("Method time invocation");
        jPanel2.add(jLabel2);

        jPanel_tab_1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 20));

        jLabel3.setText("Table is showing time in milliseconds.");
        jPanel3.add(jLabel3);

        jPanel_tab_1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 460, 20));

        jTabbedPaneMain.addTab("Medtod time invocation", jPanel_tab_1);

        javax.swing.GroupLayout jPanel_tab_2Layout = new javax.swing.GroupLayout(jPanel_tab_2);
        jPanel_tab_2.setLayout(jPanel_tab_2Layout);
        jPanel_tab_2Layout.setHorizontalGroup(
            jPanel_tab_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel_tab_2Layout.setVerticalGroup(
            jPanel_tab_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("Anomalies", jPanel_tab_2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("Compare code flow", jPanel4);

        GUI_main_panel.add(jTabbedPaneMain, java.awt.BorderLayout.CENTER);

        GUI_top_panel.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Method Trace Analyser");
        jPanel1.add(jLabel5);

        GUI_top_panel.add(jPanel1, new java.awt.GridBagConstraints());

        GUI_main_panel.add(GUI_top_panel, java.awt.BorderLayout.PAGE_START);

        GUI_bottom_text.setText("Designed and developed by team : JavaMonks CHRIST (Deemed to be University), Bangalore, INDIA");
        GUI_main_panel.add(GUI_bottom_text, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(GUI_main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(GUI_main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == browseBtn) {
            // File Chooser (Browse Tab)
            JFileChooser chooser = new JFileChooser();
            chooser.setMultiSelectionEnabled(true);
            chooser.setCurrentDirectory(SampleLogFilesFolder);
            chooser.showOpenDialog(GUI_main_panel);
            logFiles = chooser.getSelectedFiles();
            filesList = new DefaultListModel<>();
            for (File file : logFiles) {
                filesList.addElement(file);
            }
            
            updateFormOnFilesSelected();
        }
    }//GEN-LAST:event_browseBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        resetInputForm();
        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void analyseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyseBtnActionPerformed
        try {
            analyse = new Analyser(logFiles);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        //String arrData[][] = {{"Vinod","100"},{"Raju","200"},{"Ranju","300"}};
        //String arrHeadings[] = {"Name","code"};
        String arrHeadingTooltips[] = {"Name","code"};
        
        Object[][] arrData = Tools.toArray(analyse.getAnalysedTime(), (Integer) ((ArrayList) analyse.getAnalysedTime().get(0)).size());
        System.out.println(Arrays.deepToString(arrData));
        Object[] arrHeadings = (Object[]) analyse.getLogFiles().toArray();
        
        graphicalView(arrData, arrHeadings, arrHeadingTooltips);
    }//GEN-LAST:event_analyseBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        resetInputForm();
    }//GEN-LAST:event_formWindowOpened
    
    private void graphicalView(Object[][] arrData, Object[] arrHeadings, String[] arrHeadingTooltips) {
            // jPanel_Tab_TabularGraphicView.setEnabled(true);   
            jTabbedPaneMain.setEnabledAt(1, true);
            DefaultTableModel model = new DefaultTableModel(arrData,arrHeadings);
            jTable1.setModel(model); //= new JTable(model);
            
    }
    
    private void resetInputForm() {
        filesList.clear();
        jList_listOfFiles.removeAll();
        analyseBtn.setEnabled(false);
        resetBtn.setEnabled(false);
        jPanel_listing_files.setVisible(false);
        jPanel_InputForm_buttons.setVisible(false);
        browseBtn.setEnabled(true);
        jPanel_browse.setVisible(true);
        //jPanel_Tab_TabularGraphicView.setEnabled(false);
        jTabbedPaneMain.setEnabledAt(1, false);
        jTabbedPaneMain.setEnabledAt(2, false);
        jTabbedPaneMain.setEnabledAt(3, false);
        //jTabbedPaneMain.setEnabledAt(4, false);
    }
    private void updateFormOnFilesSelected() {
        jList_listOfFiles.setModel(filesList);
        analyseBtn.setEnabled(true);
        resetBtn.setEnabled(true);
        jPanel_listing_files.setVisible(true);
        jPanel_InputForm_buttons.setVisible(true);
        browseBtn.setEnabled(false);
        jPanel_browse.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GUI_bottom_text;
    private javax.swing.JPanel GUI_main_panel;
    private javax.swing.JPanel GUI_top_panel;
    private javax.swing.JButton analyseBtn;
    private javax.swing.JButton browseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_text;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<File> jList_listOfFiles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel5_main;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_InputForm_buttons;
    private javax.swing.JPanel jPanel_browse;
    private javax.swing.JPanel jPanel_listing_files;
    private javax.swing.JPanel jPanel_tab_1;
    private javax.swing.JPanel jPanel_tab_2;
    private javax.swing.JPanel jPanel_tab_home;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables

}
